require "matrix"
require "forwardable"
require "bigdecimal/util"
require "continued_fractions"
require_relative "fraction_tree/node"
require_relative "fraction_tree/extensions"
require_relative "fraction_tree/fraction_tree"
